### ISSUE TITLE
Use of command line arguments

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/GitGeo#62]
**Describe the bug**
I tried to access the command line arguments, specifically the ```help``` argument and GitGeo returned nothing. Is this the intended behavior?

**To Reproduce**
```python main.py --help```

**Expected behavior**
I expect this output:
```
usage: main.py [-h] [--package PACKAGE] [--repo REPO] [--multirepo]
               [--multirepo_map MULTIREPO_MAP] [--summary] [--output_csv]
               [--map] [--num {100,200,300,400,500}]

optional arguments:
  -h, --help            show this help message and exit
  --package PACKAGE     Specify Python (PyPI) package.
  --repo REPO           Specify GitHub repo.
  --multirepo           Scan multiple repos from input file.
  --multirepo_map MULTIREPO_MAP
                        Convert mutlirepo scan file into map.
  --summary             Display results by country.
  --output_csv          Output results in csv.
  --map                 Display country by country results in map.
  --num {100,200,300,400,500}
                        Specify max number of contributors per repo.
```

**Screenshots**
I got no output.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Python 3.7.4

**Additional context**
I replaced the main() function function definition line in main.py with this line:

```if __name__ == "__main__":```

and the program performed as I expected. Is it okay if I replace this line? Or was this change made because of the recent PyPI-package-ification changes? Thank you, @jbenjoseph!

**Comment by jbenjoseph** [comment]
This is intentional but if you want to keep main.py as an executable module, you can absolutely add the ```if ___name__``` stanza and just call ```main()``` in that block.
