### ISSUE TITLE
Multirepo scan capability now broken

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/GitGeo#63]
**Describe the bug**
The multirepo scan capability is currently broken.

**To Reproduce**
```gitgeo --multirepo```

**Expected behavior**
Scan the repos specified in repos.txt, returning a csv of contributors and their locations.

**Screenshots**
```
Traceback (most recent call last):
  File "/Users/jmeyers/opt/anaconda3/bin/gitgeo", line 8, in <module>
    sys.exit(main())
  File "/Users/jmeyers/opt/anaconda3/lib/python3.7/site-packages/gitgeo/main.py", line 123, in main
    scan_multiple_repos(num=args.num)
  File "/Users/jmeyers/opt/anaconda3/lib/python3.7/site-packages/gitgeo/multi_repo_scan.py", line 26, in scan_multiple_repos
    create_csv("multirepo", timestamp)
  File "/Users/jmeyers/opt/anaconda3/lib/python3.7/site-packages/gitgeo/custom_csv.py", line 23, in create_csv
    with open(filename, "w", encoding="utf-8", newline="") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'results/multirepo_20211104-093528.csv'
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Python 3.7.4

**Additional context**
I suspect the PyPI-ification of this package--specifically placing the Python files in a gitgeo sub-directory--is preventing the GitGeo tools from accessing the files in the results directory. Can you please advise and, if possible, fix?

**Comment by jbenjoseph** [comment]
Can you do ```ls -l``` in the directory you typed that command in and see if you have a ```results``` directory? Does ```mkdir results``` resolve the issue?

**Comment by jspeed-meyers** [comment]
@jbenjoseph, thank you for the help again. Here are my results from ```ls -l```:

```
total 1856
-rw-r--r--  1 jmeyers  764075152       0 Nov  4 14:41 __init__.py
-rw-r--r--  1 jmeyers  764075152    3619 Nov  4 14:41 country_codes.csv
-rw-r--r--  1 jmeyers  764075152    2147 Nov  4 14:41 custom_csv.py
-rw-r--r--  1 jmeyers  764075152   10359 Nov  4 14:41 geographies_list.py
-rw-r--r--  1 jmeyers  764075152    7338 Nov  4 14:41 geolocation.py
-rw-r--r--  1 jmeyers  764075152    4452 Nov  4 14:41 github.py
-rw-r--r--  1 jmeyers  764075152    4000 Nov  4 14:53 main.py
-rw-r--r--  1 jmeyers  764075152    7207 Nov  4 14:41 mapping.py
-rw-r--r--  1 jmeyers  764075152    1812 Nov  4 14:41 multi_repo_scan.py
-rw-r--r--  1 jmeyers  764075152    2507 Nov  4 14:41 printers.py
-rw-r--r--  1 jmeyers  764075152    3798 Nov  4 14:41 pypi.py
-rw-r--r--  1 jmeyers  764075152  885262 Nov  4 14:41 world_cities.csv
```
So no results directory inside the gitgeo subdirectory. The results folder is up a level.

If I create a results folder AND I move the repos.txt file to the gitgeo subfolder, then this operation works.

But then the test suite fails.

What would you like to do? I'm all for the PyPI package version, but I want to make sure all the functionality still works, especially the ```--multirepo``` functionality, which I have been using frequently.

**Comment by jbenjoseph** [comment]
We can have gitgeo create the directory if it doesn't exist. If you are with this, I will create a PR.

**Comment by jspeed-meyers** [comment]
JJ is working on a fix for this. Thank you, sir! 😄
