### ISSUE TITLE
Automatically build new package and upload to PyPi using GitHub actions

### ISSUE THREAD

**Issue by jbenjoseph** [IQTLabs/GitGeo#66]
A feature to automatically build a new package and upload it to PyPi when you push a new git tag.
The advantage is less complexity and thinking is needed on the part of the developer, as well as the git tags reflect the PyPi reality automatically.

**Comment by cglewis** [comment]
@jbenjoseph as an org we already support doing this with GHA and org-wide secrets. Here’s an example of it in practice: https://github.com/IQTLabs/NetworkML/blob/main/.github/workflows/pypi.yaml

Adding a similar yaml file to this repo will automatically push when releases/tags are made based on the name match/wildcard.
